[providers]
providers = ["php", "node"]

[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_20"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[start]
cmd = "php artisan config:clear && php artisan migrate --force --no-interaction && php artisan db:seed --force --no-interaction ; php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
